- name: "Deploy mantis stack"
  docker_service:
    state: present
    project_src: /tmp/{{ project_name }}

- name: "Repairing permissions"
  shell: |
      docker exec {{ project_name }}_mantisbt_1 bash -c "\
        chown www-data:www-data -R /var/www/html ;"

- name: "Waiting for proxy to come up..."
  when: ADD_NGINX_PROXY == True
  pause:
    seconds: 10

- name: "Getting onion url..."
  tags: show_onion
  command: docker exec -i {{ project_name }}_torhh_1 onions
  register: onions
  when: TOR_HH == True

- debug:
    msg: "Onion url: {{ onions.stdout }}"
  when: TOR_HH == True
